server:
  port: 8080
spring:
  datasource:
    username: root
    password: testtest
    url: jdbc:mysql://localhost:3306/search_engine?useSSL=false&requireSSL=false&allowPublicKeyRetrieval=true
  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL8Dialect
    hibernate:
      ddl-auto: update
    show-sql: false
logging:
  level:
    org.hibernate.SQL: OFF
    org.hibernate.type.descriptor.sql.BasicBinder: OFF


indexing-settings:
  sites:
#    - url: https://www.lenta.ru
#      name: Лента.ру
    - url: https://www.playback.ru
      name: PlayBack.Ru
#    - url: https://www.svetlovka.ru
#      name: Svetlovka
#    - url: https://dombulgakova.ru
#      name: dombulgakova
#    - url: https://dimonvideo.ru/
#      name: dimonvideo
#    - url: http://localhost:8080/pages/page1.html
#      name: Fake Page 1
#    - url: http://localhost:8080/pages/page2.html
#      name: Fake Page 2
#    - url: http://localhost:8080/pages/page3.html
#      name: Fake Page 3
#    - url: http://localhost:8080/pages/page4.html
#      name: Fake Page 4

fake:
  user-agent: "Mozilla/5.0 (Windows; U; Windows NT 5.1; en-US; rv:1.8.1.6) Gecko/20070725 Firefox/2.0.0.6"
  referrer: "http://www.google.com"
